spring.application.name=backend
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

#spring.application.name=starlink-backend
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

url-shortener.base-url=http://localhost:8080
url-shortener.short-code-length=7
url-shortener.base62-charset=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
url-shortener.default-expiry-days=1825

logging.level.com.starlink.backend=DEBUG
